version: "3"
services:
  microqr:
    container_name: microqr
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "3000:5000"
    volumes:
      - .:/microqr
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - '6379:6379'
    restart: always
    expose:
      - '6379'

volumes:
  mydatabase: